server:
  port: 9527
spring:
  application:
    name: springcloud-zuul
#    禁用安全防护
management:
  security:
    enabled: false

eureka:
  instance:
    instance-id: zuul
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

# 配置zuul的路由映射规则
zuul:
#    ignored-services: springcloud-consumer # 要用小写
  ignored-services: "*" # 忽略全部服务
  # 加统一前缀，http://myzuul.com:9527/my/mydept/dept/findById/1
  prefix: /my
  routes:
    #consumer对外暴露路径：http://localhost:9527/my/zuul/feign/dept/findAll
    springcloud-consumer: /zuul/**
    # 等价于
#    mydept:  # mydept为 路由的名称
#      serviceId: springcloud-consumer
#      path: /zuul/**

info:
  app.name: springcloud-study-zuul-gateway
  company.name: www.gxs.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
